name: 🔍 lint

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/cargo-cache
    - name: Run fmt
      run: cargo fmt --all -- --check --verbose
    - name: Run Clippy
      run: cargo clippy --all-targets --all-features